import Foundation
import SwiftData

enum MediaKind: String, Codable, CaseIterable {
    case photo
    case video
}

enum MediaSource: String, Codable {
    case camera
    case photos
    case files
}

enum AppStartScreen: String, CaseIterable, Identifiable {
    case library
    case camera
    case last

    var id: String { rawValue }

    var title: String {
        switch self {
        case .library: L10n.text("보관함")
        case .camera: L10n.text("카메라")
        case .last: L10n.text("마지막 화면")
        }
    }
}

enum StorageDestination: Equatable {
    case camera
    case all
    case temporary
    case album(UUID)

    init(token: String) {
        if token == "camera" || token.isEmpty {
            self = .camera
        } else if token == "all" {
            self = .all
        } else if token == "temporary" {
            self = .temporary
        } else {
            let rawID = token.hasPrefix("album:") ? String(token.dropFirst("album:".count)) : token
            self = UUID(uuidString: rawID).map(Self.album) ?? .all
        }
    }

    var token: String {
        switch self {
        case .camera: "camera"
        case .all: "all"
        case .temporary: "temporary"
        case .album(let id): "album:\(id.uuidString)"
        }
    }
}

enum RetentionPolicy: String, Codable, CaseIterable, Identifiable {
    case forever
    case today
    case oneDay
    case sevenDays
    case thirtyDays
    case customDate
    case untilComplete

    var id: String { rawValue }

    var title: String {
        switch self {
        case .today: L10n.text("오늘까지")
        case .oneDay: L10n.text("24시간")
        case .sevenDays: L10n.text("7일")
        case .thirtyDays: L10n.text("30일")
        case .customDate: L10n.text("날짜 지정")
        case .untilComplete: L10n.text("완료할 때까지")
        case .forever: L10n.text("계속 보관")
        }
    }

    func expiration(from date: Date = .now) -> Date? {
        let calendar = Calendar.current
        switch self {
        case .today: return calendar.date(bySettingHour: 23, minute: 59, second: 59, of: date)
        case .oneDay: return calendar.date(byAdding: .day, value: 1, to: date)
        case .sevenDays: return calendar.date(byAdding: .day, value: 7, to: date)
        case .thirtyDays: return calendar.date(byAdding: .day, value: 30, to: date)
        case .customDate, .untilComplete, .forever: return nil
        }
    }
}

enum OCRStatus: String, Codable {
    case pending
    case processing
    case completed
    case failed
    case notApplicable
}

enum CapturePurpose: String, Codable, CaseIterable, Identifiable {
    case general
    case receipt
    case parking
    case document
    case qr
    case temporary
    case travel
    case custom

    var id: String { rawValue }

    var title: String {
        switch self {
        case .general: L10n.text("일반")
        case .receipt: L10n.text("영수증")
        case .parking: L10n.text("주차")
        case .document: L10n.text("문서")
        case .qr: L10n.text("QR")
        case .temporary: L10n.text("임시 사진")
        case .travel: L10n.text("여행")
        case .custom: L10n.text("사용자 설정")
        }
    }
}

enum SmartClassificationStatus: String, Codable {
    case none
    case pending
    case suggested
    case dismissed
    case applied
}

enum PrimaryMediaAction: String, Codable, CaseIterable, Identifiable {
    case automatic
    case shareAndComplete
    case findCar
    case copyAndComplete
    case open
    case addEvent

    var id: String { rawValue }

    var title: String {
        switch self {
        case .automatic: L10n.text("자동 선택")
        case .shareAndComplete: L10n.text("공유하고 완료")
        case .findCar: L10n.text("차 찾기")
        case .copyAndComplete: L10n.text("복사하고 완료")
        case .open: L10n.text("열기")
        case .addEvent: L10n.text("일정 추가")
        }
    }
}

@Model
final class MediaItem {
    // CloudKit does not support Core Data uniqueness constraints. UUIDs are
    // generated by the app and remain the stable identity across devices.
    var id: UUID = UUID()
    var kindRaw: String = MediaKind.photo.rawValue
    var sourceRaw: String = MediaSource.files.rawValue
    var localPath: String = ""
    var thumbnailPath: String?
    @Attribute(.externalStorage) var cloudMediaData: Data?
    @Attribute(.externalStorage) var cloudThumbnailData: Data?
    var createdAt: Date = Date.now
    var importedAt: Date = Date.now
    var albumID: UUID?
    var favorite: Bool = false
    var expirationTypeRaw: String = "forever"
    var expirationDate: Date?
    var waitingForCompletion: Bool = false
    var isPinned: Bool = false
    var reminderDate: Date?
    var reminderIdentifier: String?
    var recognizedText: String = ""
    var ocrStatusRaw: String = "notApplicable"
    var fileName: String = ""
    var note: String = ""
    var deletedAt: Date?
    var fileSize: Int64 = 0
    var width: Int = 0
    var height: Int = 0
    var duration: Double = 0
    var latitude: Double?
    var longitude: Double?
    var analysisEnabled: Bool = true
    var purposeRaw: String = "general"
    var primaryActionRaw: String = "automatic"
    var detectedURLsJSON: String = "[]"
    var detectedPhoneNumbersJSON: String = "[]"
    var detectedAddressesJSON: String = "[]"
    var detectedDatesJSON: String = "[]"
    var detectedQRCodesJSON: String = "[]"
    var receiptMerchant: String = ""
    var receiptAmount: String = ""
    var receiptDate: Date?
    var completedAt: Date?
    var completionRestorePinned: Bool = false
    var completionRestoreWaiting: Bool = false
    var completionRestoreExpirationTypeRaw: String = "forever"
    var completionRestoreExpirationDate: Date?
    var completionRestoreReminderDate: Date?
    var classificationStatusRaw: String = SmartClassificationStatus.none.rawValue
    var suggestedPurposeRaw: String?
    var suggestedAlbumID: UUID?
    var suggestedRetentionRaw: String?
    var premiumAnalysisVersion: Int = 0

    init(
        id: UUID = UUID(), kind: MediaKind, source: MediaSource,
        localPath: String, thumbnailPath: String? = nil,
        fileName: String? = nil,
        createdAt: Date = .now, albumID: UUID? = nil,
        expirationDate: Date? = nil, fileSize: Int64 = 0,
        width: Int = 0, height: Int = 0, duration: Double = 0
    ) {
        self.id = id
        self.kindRaw = kind.rawValue
        self.sourceRaw = source.rawValue
        self.localPath = localPath
        self.thumbnailPath = thumbnailPath
        self.cloudMediaData = try? Data(contentsOf: MediaStorage.url(for: localPath), options: .mappedIfSafe)
        self.cloudThumbnailData = thumbnailPath.flatMap {
            try? Data(contentsOf: MediaStorage.url(for: $0), options: .mappedIfSafe)
        }
        self.createdAt = createdAt
        self.importedAt = .now
        self.albumID = albumID
        self.favorite = false
        self.expirationTypeRaw = RetentionPolicy.forever.rawValue
        self.expirationDate = expirationDate
        self.waitingForCompletion = false
        self.isPinned = false
        self.reminderDate = nil
        self.reminderIdentifier = nil
        self.recognizedText = ""
        self.ocrStatusRaw = kind == .photo ? OCRStatus.pending.rawValue : OCRStatus.notApplicable.rawValue
        self.fileName = fileName ?? URL(fileURLWithPath: localPath).lastPathComponent
        self.note = ""
        self.deletedAt = nil
        self.fileSize = fileSize
        self.width = width
        self.height = height
        self.duration = duration
        self.classificationStatusRaw = kind == .photo
            ? SmartClassificationStatus.pending.rawValue
            : SmartClassificationStatus.none.rawValue
    }

    var kind: MediaKind { MediaKind(rawValue: kindRaw) ?? .photo }
    var source: MediaSource { MediaSource(rawValue: sourceRaw) ?? .files }
    var mediaURL: URL {
        MediaStorage.materializedURL(for: localPath, cloudData: cloudMediaData)
    }
    var thumbnailURL: URL? {
        guard let thumbnailPath else { return nil }
        return MediaStorage.materializedURL(for: thumbnailPath, cloudData: cloudThumbnailData)
    }
    var expirationType: RetentionPolicy {
        get { RetentionPolicy(rawValue: expirationTypeRaw) ?? (expirationDate == nil ? .forever : .customDate) }
        set { expirationTypeRaw = newValue.rawValue }
    }
    var ocrStatus: OCRStatus {
        get { OCRStatus(rawValue: ocrStatusRaw) ?? .pending }
        set { ocrStatusRaw = newValue.rawValue }
    }
    var purpose: CapturePurpose {
        get { CapturePurpose(rawValue: purposeRaw) ?? .general }
        set { purposeRaw = newValue.rawValue }
    }
    var primaryAction: PrimaryMediaAction {
        get { PrimaryMediaAction(rawValue: primaryActionRaw) ?? .automatic }
        set { primaryActionRaw = newValue.rawValue }
    }
    var classificationStatus: SmartClassificationStatus {
        get { SmartClassificationStatus(rawValue: classificationStatusRaw) ?? .none }
        set { classificationStatusRaw = newValue.rawValue }
    }
    var suggestedPurpose: CapturePurpose? {
        get { suggestedPurposeRaw.flatMap(CapturePurpose.init(rawValue:)) }
        set { suggestedPurposeRaw = newValue?.rawValue }
    }
    var suggestedRetention: RetentionPolicy? {
        get { suggestedRetentionRaw.flatMap(RetentionPolicy.init(rawValue:)) }
        set { suggestedRetentionRaw = newValue?.rawValue }
    }
    var detectedURLs: [String] {
        get { Self.decodeStrings(detectedURLsJSON) }
        set { detectedURLsJSON = Self.encode(newValue) }
    }
    var detectedPhoneNumbers: [String] {
        get { Self.decodeStrings(detectedPhoneNumbersJSON) }
        set { detectedPhoneNumbersJSON = Self.encode(newValue) }
    }
    var detectedAddresses: [String] {
        get { Self.decodeStrings(detectedAddressesJSON) }
        set { detectedAddressesJSON = Self.encode(newValue) }
    }
    var detectedDates: [Date] {
        get { Self.decodeDates(detectedDatesJSON) }
        set { detectedDatesJSON = Self.encode(newValue.map(\.timeIntervalSince1970)) }
    }
    var detectedQRCodes: [String] {
        get { Self.decodeStrings(detectedQRCodesJSON) }
        set { detectedQRCodesJSON = Self.encode(newValue) }
    }
    var analysisSearchText: String {
        ([recognizedText, receiptMerchant, receiptAmount]
            + detectedURLs + detectedPhoneNumbers + detectedAddresses + detectedQRCodes)
            .filter { !$0.isEmpty }
            .joined(separator: "\n")
    }

    private static func encode<T: Encodable>(_ value: T) -> String {
        guard let data = try? JSONEncoder().encode(value) else { return "[]" }
        return String(decoding: data, as: UTF8.self)
    }

    private static func decodeStrings(_ value: String) -> [String] {
        (try? JSONDecoder().decode([String].self, from: Data(value.utf8))) ?? []
    }

    private static func decodeDates(_ value: String) -> [Date] {
        let values = (try? JSONDecoder().decode([Double].self, from: Data(value.utf8))) ?? []
        return values.map(Date.init(timeIntervalSince1970:))
    }
}

@Model
final class Album {
    var id: UUID = UUID()
    var name: String = ""
    var createdAt: Date = Date.now
    var sortOrder: Int = 0
    var coverMediaID: UUID?
    var defaultRetentionRaw: String = RetentionPolicy.forever.rawValue
    var defaultRetentionDate: Date?
    var purposeRaw: String = "custom"
    var ocrEnabled: Bool = true
    var savesLocation: Bool = false
    var autoPins: Bool = false
    var primaryActionRaw: String = "automatic"
    var isBuiltIn: Bool = false
    var smartRuleEnabled: Bool = false
    var smartRuleKeywords: String = ""

    init(name: String, sortOrder: Int = 0, defaultRetention: RetentionPolicy = .forever) {
        self.id = UUID()
        self.name = name
        self.createdAt = .now
        self.sortOrder = sortOrder
        self.coverMediaID = nil
        self.defaultRetentionRaw = defaultRetention.rawValue
        self.defaultRetentionDate = nil
    }

    var defaultRetention: RetentionPolicy {
        get { RetentionPolicy(rawValue: defaultRetentionRaw) ?? .forever }
        set { defaultRetentionRaw = newValue.rawValue }
    }
    var purpose: CapturePurpose {
        get { CapturePurpose(rawValue: purposeRaw) ?? .custom }
        set { purposeRaw = newValue.rawValue }
    }
    var primaryAction: PrimaryMediaAction {
        get { PrimaryMediaAction(rawValue: primaryActionRaw) ?? .automatic }
        set { primaryActionRaw = newValue.rawValue }
    }
    var displayName: String { isBuiltIn ? purpose.title : name }
}

@Model
final class CapturePreset {
    var id: UUID = UUID()
    var name: String = ""
    var albumID: UUID?
    var retentionRaw: String = RetentionPolicy.sevenDays.rawValue
    var savesLocation: Bool = false
    var aspectRatio: String = "4:3"
    var captureMode: String = "photo"
    var purposeRaw: String = "custom"
    var ocrEnabled: Bool = true
    var autoPins: Bool = false
    var primaryActionRaw: String = "automatic"
    var sortOrder: Int = 0
    var isBuiltIn: Bool = false

    init(name: String, albumID: UUID? = nil, retention: RetentionPolicy = .sevenDays) {
        self.id = UUID()
        self.name = name
        self.albumID = albumID
        self.retentionRaw = retention.rawValue
        self.savesLocation = false
        self.aspectRatio = "4:3"
        self.captureMode = "photo"
    }

    var retention: RetentionPolicy {
        get { RetentionPolicy(rawValue: retentionRaw) ?? .forever }
        set { retentionRaw = newValue.rawValue }
    }
    var purpose: CapturePurpose {
        get { CapturePurpose(rawValue: purposeRaw) ?? .custom }
        set { purposeRaw = newValue.rawValue }
    }
    var primaryAction: PrimaryMediaAction {
        get { PrimaryMediaAction(rawValue: primaryActionRaw) ?? .automatic }
        set { primaryActionRaw = newValue.rawValue }
    }
    var displayName: String { isBuiltIn ? purpose.title : name }
}
